codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80
    patch: false
    changes: false

comment:
  layout: "diff, flags, files"
  behavior: once
  require_base: no
