name: Build and Test

on:
  push:
    paths:
      - 'scFates/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get clean && sudo apt-get update
        sudo apt-get install -y r-base r-cran-mgcv
        pip install rpy2
        pip install wheel coverage cmake pytest mock git+https://github.com/j-bac/elpigraph-python.git
        pip install .
    - name: Test with pytest
      run: |
        coverage run -m pytest scFates/tests/test_w_plots.py
        coverage report -m
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
