name: Build Wheels

on:
  push:
    tags: ['v*']
    branches: ['*dev']

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, 'pypi test') ||
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel

      - name: Build wheel
        run: |
          python setup.py bdist_wheel
          python setup.py sdist


      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
        if: contains(github.event.head_commit.message, 'pypi test')

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
        if: startsWith(github.ref, 'refs/tags/v')
