name: Build and Test

on: push

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7,3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get clean && sudo apt-get update
        sudo apt-get install -y r-base r-cran-mgcv
        pip install cmake pytest mock git+https://github.com/j-bac/elpigraph-python.git
        pip install .
    - name: Test with pytest
      run: |
        pytest -s scFates/tests/test_wo_plots.py
