name: docker_upload

on:
  push:
    tags: ['v*']
    branches: ['*dev']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: louisfaure/scfates:${{ github.ref_name }},louisfaure/scfates:latest
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Build and push test
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: louisfaure/scfates:${{ github.ref_name }}
        if: contains(github.event.head_commit.message, 'docker test')
